sudo: false
language: ruby
cache: bundler
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_0.gemfile
script: "bundle exec rake test"
